version: "3.5"
services:
  postgres:
    container_name: ninja_db
    image: postgres:13.3
    environment:
      - POSTGRES_USER=ninja
      - POSTGRES_PASSWORD=5427
    ports:
      - "5432:5432"
  
  nginx:
    image: nginx:stable-alpine
    ports:
    - "8080:80"
    volumes:
    - ./nginx.conf:/usr/local/etc/nginx/nginx.conf:ro
