version: "3.9"

services:
  api:
    container_name: api
    build: .
    environment:
      DATABASE_URL: "host=db user=skillbox dbname=skillbox sslmode=disable password=5427"
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13.3
    environment:
      POSTGRES_USER: skillbox
      POSTGRES_PASSWORD: 5427
      POSTGRES_DB: skillbox
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/potgresql/data

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  pgdata: {}
