version: "3.6"
services:

  postgres:
      container_name: ninja_db
      image: postgres:13.3
      environment:
        - POSTGRES_USER=ninja
        - POSTGRES_PASSWORD=5427
      ports:
        - "5432:5432"

  api:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - postgres

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
    

 
